### ISSUE TITLE
Create builder for Move

### ISSUE THREAD

**Issue by lispking** [amp-buildpacks/move-builder#1]
* create template for [packer tools](https://github.com/amp-buildpacks/packer), like `config.toml`

```toml
[[dependencies]]
repo = "amp-buildpacks/move"
version = "0.1.0"
```

* create builder

```bash
packer init -t builder -c config.toml
```
